baseURL: 'http://example.org/'
languageCode: de
title: Home
theme: PaperMod
publishDir: 'docs'

enableEmoji: true
buildDrafts: false

params:
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: true # to switch between dark or light according to browser theme
    disableThemeToggle: false
    ShowReadingTime: true
    ShowWordCount: true

    homeInfoParams:
        Title: "Welcome here \U0001F44B"
        Content: It's just a travel Blog

    hideFooter: false
    DateFormat: "Monday, January 2, 2006" #"2006-01-02 15:04"

menu:
    main:
      - name: About
        url: about/
        weight: 1
      - name: Archive
        url: archives/
        weight: 2
      - name: Tags
        url: tags/
        weight: 3
